import colors from './colors';

export default {
  stepIndicatorSize: 30,
  currentStepIndicatorSize: 30,
  separatorStrokeWidth: 2,
  currentStepStrokeWidth: 1,
  stepStrokeCurrentColor: colors.secondary,
  stepStrokeWidth: 2,
  stepStrokeFinishedColor: colors.secondary,
  stepStrokeUnFinishedColor: colors.white,
  separatorFinishedColor: colors.secondary,
  separatorUnFinishedColor: colors.secondary,
  stepIndicatorFinishedColor: colors.white,
  stepIndicatorUnFinishedColor: colors.secondary,
  stepIndicatorCurrentColor: colors.white,
  stepIndicatorLabelFontSize: 12,
  currentStepIndicatorLabelFontSize: 11,
  stepIndicatorLabelCurrentColor: colors.black,
  stepIndicatorLabelFinishedColor: colors.white,
  stepIndicatorLabelUnFinishedColor: colors.light,
  labelColor: colors.primary,
  labelSize: 9,
  currentStepLabelColor: colors.grey_medium,
};
