import colors from './colors';

export default {
  stepIndicatorSize: 30,
  currentStepIndicatorSize: 30,
  separatorStrokeWidth: 2,
  currentStepStrokeWidth: 1,
  stepStrokeCurrentColor: colors.light_grey,
  stepStrokeWidth: 2,
  stepStrokeFinishedColor: colors.light_grey,
  stepStrokeUnFinishedColor: colors.light,
  separatorFinishedColor: colors.blue,
  separatorUnFinishedColor: colors.light,
  stepIndicatorFinishedColor: colors.darkBlue,
  stepIndicatorUnFinishedColor: colors.darkBlue,
  stepIndicatorCurrentColor: colors.darkBlue,
  stepIndicatorLabelFontSize: 12,
  currentStepIndicatorLabelFontSize: 11,
  stepIndicatorLabelCurrentColor: colors.black,
  stepIndicatorLabelFinishedColor: colors.white,
  stepIndicatorLabelUnFinishedColor: colors.light,
  labelColor: colors.medium,
  labelSize: 12,
  currentStepLabelColor: colors.black,
};
